spring.application.name=LoginSystem
spring.profiles.default=local

spotify.client.id=${SPOTIFY_CLIENT_ID}
spotify.client.secret=${SPOTIFY_CLIENT_SECRET}
spotify.redirect.uri=${SPOTIFY_REDIRECT_URI}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.cache.caffeine.spec=expireAfterWrite=10m
gemini.api.key=${GEMINI_API_KEY:}
